#!/bin/sh
#husky 0.14.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

# OS X and Linux only
load_nvm () {
  # If nvm is not loaded, load it
  command_exists nvm || {
    export NVM_DIR="$1"
    [ -s "$1/nvm.sh" ] && . "$1/nvm.sh"
  }
}

# OS X and Linux only
run_nvm () {
  # If nvm has been loaded correctly, use project .nvmrc
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

cd "."

# Check if changegroup script is defined, skip if not
has_hook_script changegroup || exit 0

# Node standard installation
export PATH="$PATH:/c/Program Files/nodejs"

# Check that npm exists
command_exists npm || {
  echo >&2 "husky > can't find npm in PATH, skipping changegroup script in package.json"
  exit 0
}

# Export VCS hook params
export HG_ARGS="$*"

# Run npm script
echo "husky > npm run -s changegroup (node `node -v`)"
echo

npm run -s changegroup || {
  echo
  echo "husky > changegroup hook failed (add --no-verify to bypass)"
  exit 1
}
